dist: bionic
language: csharp
dotnet: "2.2"
mono: none

env:
  global:
    - PATH="$PATH:$HOME/.dotnet/tools"

install:
  - dotnet tool install -g paket

script:
 - paket install
 - dotnet restore
 - dotnet build
 - dotnet test
